#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):
    D = [0]*(n+1)

    for y in queries:
        D[y[0]-1] += y[2]
        D[y[1]] -= y[2]

    mx = -10**7
    val = D[0]
    new_val = 0
    for i in range(1,n):
        new_val = val + D[i]
        val = new_val
        if new_val>mx:
            mx = new_val
    return mx
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
